# Imports

[common]
sign = """/*	Project: $project$
         __ 
     |_|(_   
     | |__)
    Author: $author$
    Date: $DATE$   
*/"""

[gitignore]

tex = """
# Latex Auxillary Files
*.aux
*.lof
*.log
*.lot
*.fls
*.out
*.toc
*.fmt
*.fot
*.cb
*.cb2
.*.lb

"""
# compressed files
compressed = """
# Compressed Files
*.7z
*.gz
*.rar
*.tar
*.zip
"""

# Windows specific files
windows = """
# Windows Thumbnail Database
Thumbs.db
"""

[tex]
ele_setup = ''' %% Circuit tikz setup
\usepackage[RPvoltages]{circuitikz}
\usepackage{MnSymbol}'''

def_setup = '''
\documentclass[english]{article}
\usepackage[utf8]{inputenc}
\usepackage{float}
\usepackage{fancyhdr}
\usepackage{hyperref}
\usepackage{ulem}
\usepackage{amsmath}
\pagenumbering{arabic}
\usepackage{mathtools}
\usepackage{enumerate}'''

img_setup = '''
\usepackage{graphicx}
\graphicspath{{img/}}'''

front_page = ''' % Page setup
\pagestyle{fancy}
\fancyhf{}
\rhead{<++>} % Right head
\lhead{<++>} % Left head
\rfoot{\thepage}
\lfoot{\author}'''

flow_chart = '''%% tikz
\usepackage{tikz}
\usetikzlibrary{shapes,arrows}
\tikzstyle{start} = [rectangle, rounded corners,text centered, draw=black, minimum width=3cm, minimum height=0.8cm, fill=red!20]
\tikzstyle{block} = [rectangle, minimum width=3cm, minimum height=0.8cm, text centered, draw=black,fill=black!20]
\tikzstyle{if} = [diamond, minimum width=5cm, text centered, draw=black, aspect=2,fill=green!20]
\tikzstyle{nan} = [rectangle, draw=white]
\tikzstyle{arrow} = [thick,->,>=stealth]'''
