[variables]
author = "Håvard Syslak"
email = "haavard.syslak@gmail.com"

[c]
gitignore = true
makefile = true

[go]
gitignore = true
makefile = true

[tex]
gitignore = false
makefile = false

[org]
gitignore = false
makefile = false
overridable = false
