[variables]
author = "Håvard Syslak"
email = "haavard.syslak@gmail.com"

[c]
gitignore = true
makefile = true

[go]
gitignore = true
makefile = true

[tex]
gitignore = false
makefile = false

[org]
gitignore = false
makefile = false
overridable = false

[h] # Headder files
gitignore = false
makefile = false
overridable = false # never move git/make files when creating single headder files

