
[colors.normal]
black = "#282828"
blue = "#7070ff"
cyan = "#a9a9a9"
green = "#00ff00"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#70f050"


[colors.primary]
background = "#1c1f24"
# text = "#e3e3e3"

[env]
TERM = "alacritty"

[font]
size = 7

[font.normal]
family = "JetBrains Mono"

[scrolling]
history = 10000
multiplier = 1

[window]
dynamic_title = true
# opacity = 0.96
